### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by j143** [j143/codelabs-template#4]
**next:**
- [ ] Add support for google docs, generate based on this: 1x3NUWGle3xOW0n3y75tlp9fz67Gg
      - need to have a token for the repository
      - for now, just go with this simple method
        
      claat export -f md  1x3NUWGle3xOW0n3y75tlp9djABZOoFofs 
      ok      your-first-pwapp
      
- [ ] Add codelabs homepage to serve the labs. This one: https://github.com/googlecodelabs/tools/tree/main/site 

**nice to have:**
- [ ] create a pull request action, so that updates to markdown generates html and a pull request will be created.
- [ ] fix this upgrade action (https://github.com/j143/codelabs-template/blob/main/.github/workflows/update.yml)
      -  so that if people use this template then the upgrade will be easier
      - Let's wait for sufficient users to work on this feature.
